### ISSUE TITLE
If a user edits their approved operation, the confirmation message is outdated

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#1322]
#### Describe the task

After an operation is approved, a user can edit it by returning to the form and clicking "save and continue"/"submit". When they click submit, they receive this message:

![Image](https://github.com/bcgov/cas-registration/assets/77306764/3a976a06-9dde-4966-aff4-ce162b37a8d7)

The message says "once approved" but the operation has already been approved. 

#### Acceptance Criteria

- [x] Update the message to "Your changes have been saved."

**Comment by BCerki** [comment]
@nanyangpro or @zoeyli-46, I don't think we ever had a confirmation message for this situation. What do you suggest?

**Comment by nanyangpro** [comment]
Hi @hannavovk & @zoeyli-46 - I feel I may lack context of the situation as described by @BCerki in the ticket description for Reg Pt. 1, thus needing your help confirming the intended behaviour to ensure I provide accurate messaging:
- When user makes edits to an already approved BORO ID application, would the status of the application go back to "Pending Approval"?
- In that case, would the already issued BORO ID be invalidated before the application is approved again?
- When approved again by IRC, would a new BORO ID be issued or the old one remains valid?

**Comment by hannavovk** [comment]
What if we just said "Your changes have been saved. " and leave it at that? I think unless we tell them that their BORO ID is impacted there's no reason for them to think otherwise.  If others disagree though then I'm okay with keeping the second sentence as well just without the typo :). So in sum: "Your changes have been saved. The previously issued B.C. OBPS Regulated Operation ID remains valid." (cc @nanyangpro @zoeyli-46 )
Also, let's add this to the ticket description (or acceptance criteria).

**Comment by nanyangpro** [comment]
Sounds good to me, thanks @hannavovk. The AC has been updated.

**Comment by BCerki** [comment]
Might need to update the messaging in the email too

**Comment by BCerki** [comment]
@nanyangpro , as I was doing this ticket I noticed that the `Have not received the confirmation email yet?` doesn't actually link anywhere. I can add a link as part of this ticket if we know where it's supposed to go.
