### ISSUE TITLE
Add dev documentation for working on Registration Parts 1&2 simultaneously

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1619]
#### Describe the task

Write documentation (for developer usage) describing how to work on Registration Parts 1 and 2.

#### Acceptance Criteria

- [x] add new .md file in `/docs` folder of codebase
- [x] include instructions for how to add/edit API endpoints for Registration Parts 1 & 2 (including pytests)
- [x] include instructions for how to add/edit database models for Registration Parts 1 & 2 (including model tests) Pasted in a comment below or grab them from this PR: https://github.com/bcgov/cas-registration/pull/1654/files

#### Additional context

- Blocking #1577 ,  cas-obps 258 (Done)
- Blocked by #1628

**Comment by BCerki** [comment]
Models docs, @Sepehr-Sobhani has already weighed in:

## Models and Model Tests

If possible, we want to use the same models for parts 1 and 2. We'll achieve this mainly with use of `null=True`.

You can find the models in `/cas-registration/bc_obps/registration/models.py` and the tests in `bc_obps/registration/tests/test_models.py`.

If you need to add something new, you can directly edit `/cas-registration/bc_obps/registration/models.py`:

- If you're creating a new table, add it as normal
- If you're adding a column to an existing table, it needs to be nullable so that reg part 1 can continue to use the existing table. Set `(null=True)` and `(blank=True)` (null is for the db and blank is for django forms)
- Create and run migrations
- Add tests to `bc_obps/registration/tests/test_models.py`

If data is no longer necessary for part 2 but existed in part 1:

- Set the column to nullable and blank in `/cas-registration/bc_obps/registration/models.py`
- Run migrations
- No test updates needed--we don't test if fields are mandatory or not

If you need to change something:

- See if it's possible to make the change in a way to make the existing models work for both parts 1 and 2. For example, in part 1 we have `operation_type` as a `CharField`, and in part 2 it will be a foreign key field to an `OperationType` models. We can add the part 1 types (they were selected via dropdown so only a few options) to to the `OperationType` model so that both parts 1 and 2 can use the foreign key table.
- If it's not possible to use the same models, we'll have to look into field or model versioning. E.g. of field versioning: we have data_field, create data_field_1, and we can remove data_field and rename data_field_1 to data_field once we are done with reg part 2.

**Comment by marcellmueller** [comment]
Looks like this issue is api/database specific but for future reference I added some basic documentation for working on both frontend applications here: https://github.com/bcgov/cas-registration/blob/develop/docs/registration_part_2/frontend-development.md
