### ISSUE TITLE
Address Figma comments on Registration wireframes

### ISSUE THREAD

**Issue by suhafa** [bcgov/cas-registration#168]
#### Describe the task

As part of the hand-off and working on user flows, we've added comments over Figma for to-do work as well as generics comments for future work. This ticket is for resolving those comments and mapping out future design work.

#### Acceptance Criteria

- [x] review comments on figma 
- [x] create wireframes as suited addressing those tickets
- [x] resolve the comments
- [x] document future exploratory design work (if any)

#### Additional context

- Add any other context about the task here.
- Or here

**Comment by suhafa** [comment]
Notes of changes made (ongoing):
- Changed app name to BC OBPS in wireframes

**Comment by suhafa** [comment]
@hannavovk hey Hanna! This is the ticket to capture all the Figma wireframe refining. I'm working on this within this sprint and it will be ongoing work. Which pipeline should I keep this going in? @Dianadec would you have any suggestions for this?

**Comment by Dianadec** [comment]
@suhafa if it is ongoing work, here's some suggestions:
- If there is any way to separate this type of work into tasks according to the workflow theme, you could pull those specific ones into "in progress" and keep the others in the sprint backlog. That way, the team/PO will know which ones are currently being worked on. Then when you are working on something else, pull them out of the in-progress pipeline. They can move back and forth.
- If it's an an ongoing piece of work, the tasks can sometimes be glossed over and travel across sprints which we try to avoid. but I understand the nature of this work that naturally does this. But that's why I suggest the point above to make the tasks more specific, only if it makes sense to do that and doesn't cause too much process overhead. Happy to chat more about this :). cc @hannavovk

**Comment by suhafa** [comment]
@hannavovk Hi Hanna! This ticket is ready for your review. A total of 29 comments on Figma were resolved. You can view which ones by going into Figma and clicking on this button:
[Uploading... image.png]

**Comment by hannavovk** [comment]
Awesome! Thanks @suhafa! Closing this ticket and assuming we create a new ticket for all the new stuff we talked about yesterday.
