### ISSUE TITLE
Explore networking solutions

### ISSUE THREAD

**Issue by mikevespi** [bcgov/cas-registration#188]
Being deployed using a micro-service architecture approach puts extra emphasis on handling external traffic in a secure manner. There are a couple of approaches that could be taken. Since we are deploying to a kubernetes cluster we can use Ingress / and ingress controller, which is k8s version of a reverse proxy. Another option would be an API gateway; however this is not the only solution and alternatives should be explored. On top of our external traffic, our solution will need to handle pod-pod, and pod-service traffic as well.

**Comment by joshgamache** [comment]
With some limited inspection, it seems OpenShift's Service Mesh (their implementation of Istio) is not available on the Silver cluster. And due to some permissions we'd likely need, I imagine we couldn't [implement it ourselves](https://istio.io/latest/docs/setup/platform-setup/openshift/) either. 
I had explored
