### ISSUE TITLE
Can't submit the facility form for an LFO [8]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#2203]
Describe the Bug:

When you click "Save and Continue," the button goes grey but you're never redirected to the next step: https://www.loom.com/share/dab33f8a692f470599df2bd106433e26. Operation 2 is our mock LFO.

SFOs seem to work fine.

Probability (how likely the bug is to happen, scored from 1-5): 5?
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by marcellmueller** [comment]
I looked into this because it was previously working and it's the small bugfix for the DataGrid empty rows that caused this to break. I'm not exactly why this one line fix caused it though from my work on the Facility DataGrid issue I know that the `router.push` in the form page change sometimes causes the DataGrid to refresh due to the query param change and stops the page transition.
