### ISSUE TITLE
Administration - Operation DataGrid action cell - link to Registration form

### ISSUE THREAD

**Issue by marcellmueller** [bcgov/cas-registration#2270]
#### Describe the task

The Operation Datagrid in the Administration app action cell links to the `Operation Details` form when the links say `Start Registration` - This should bring the user to the `Register an Operation` page with some of the form data pre-populated.

#### Acceptance Criteria

- [x] `Start Registration` action cell link brings the user to the `Register an Operation` form
- [x] `Continue Registration` action cell link brings the user to the `Register an Operation` form
- [x]  `View Operation` action cell link remains the same and brings the user to the `Operation details` form

**Comment by BCerki** [comment]
We don't currently have a flow (either in the app or the prototypes, I believe) for continuing a registration:
- You can't get back into an existing registration from the registration tile. If you click "Register an Operation," only operations that haven't been started show in the dropdown
- We haven't built a way to show previously entered information for all of the form steps. This means that if you click the "back" button, sometimes you'll see an empty form instead of the information you entered. The info you entered IS saved in the db, but you can't see it (unless you go look in admin)
- If you click "Continue Registration" from the operations grid, where should you be sent? The first step of the workflow with previously entered information showing, and then you click through from there? That would be easier than sending you to the most recently completed step
