### ISSUE TITLE
IDIR users' codes go into the db in the first and last name fields

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#447]
Describe the Bug:

Do we need to clean IDIRs before putting them in the db? <img width="1760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK056QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--99fba96f5771829f7ddabd1a8d4304392297ac01/image.png" alt="image.png" />

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by marcellmueller** [comment]
@BCerki I think we can close this as this as our IDIRs themselves are the issues and are being fixed?

**Comment by BCerki** [comment]
> @BCerki I think we can close this as this as our IDIRs themselves are the issues and are being fixed?

I'd like to get Dylan's opinion before closing because this might affect users besides contractors. If it does, there might already be a solution in CIIP/CIF we could reuse

**Comment by dleard** [comment]
Ah, I see what's going on here. We're using a different name attribute from the jwt in this app than we have in previous apps. In CIF & CIIP we use the `given_name` and `family_name` attributes of the jwt ([here](https://github.com/bcgov/cas-cif/blob/e4e1523f6da4acfe2069777a8569618849e1ae11/schema/deploy/mutations/update_or_create_user_from_session.sql#L21) in CIF). These attributes do not include the ministry codes.

I think we should parse these attributes from the jwt and add them to the session & use them instead of the .name attribute when creating the user.
