### ISSUE TITLE
External users can't request access to operators that already have an admin [7]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#770]
Describe the Bug:

Bug encountered in TEST env by CAS staff using their Business BCeID accounts. AJ has admin powers as an external user to operator named "BC test 2024-1". JM then followed the workflow to request access to this operator, and after clicking the "Request Access" button, got an error message saying "Your business bceid does not match that of the approved admin." (see screenshot below)

This means that external users can't request access to their operator if they aren't the prime admin.

Probability (how likely the bug is to happen, scored from 1-5): 4 (?)
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

![Image](https://github.com/bcgov/cas-registration/assets/54914403/ac582bc1-e40f-41e3-9910-e0c36ed5f746)

Additional information:

- observed in TEST env on afternoon of Mon Jan 29
- log in backend pod shows `10.97.105.50 - - [30/Jan/2024:00:12:47 +0000] "POST /api/registration/select-operator/request-access HTTP/1.1" 403 77 "-" "undici"`

Preliminary Investigation:
- both users are part of the same Business BCeID parent account, so their `business_guid` values should match. However, the business_guids are being randomly generated and stored to the database, so they never match. The fix: we should not be randomly generating `business_guid` values, they should be getting pulled from actual user session data received from Keycloak.

**Comment by dleard** [comment]
I see in the /user POST api that we're not saving the business guid to the database & that our User model has a default. The business_guid field in the model shouldn't have a default and shouldn't be nullable & we need to save the business_guid when we save the user. Since the field has a default & we're not saving anything, Django is auto-generating a random uuid to populate that business_guid field.

The protection is working as expected though, if a user's business guid doesn't match the admin's then they should not be able to request access to that operator
