### ISSUE TITLE
Can't submit operations form [8]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#830]
Describe the Bug:

422 error

Probability (how likely the bug is to happen, scored from 1-5): 4
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:
On develop branch
https://www.loom.com/share/f67d2cc240334be4902cbb2ce9457a46?focus_title=1&muted=1&from_recorder=1
![image](https://github.com/bcgov/cas-registration/assets/77306764/1053e870-af85-4edb-b625-28b492813b28)

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by Sepehr-Sobhani** [comment]
Hey @marcellmueller ! I came across this issue while working on optimization, and I wanted to share it with you since you're working on this bug. I believe that we can avoid an unnecessary API call on the front-end to retrieve the operator associated with the user. Instead, we can get that operator in the backend and assign it to the operation and save some time. Here is my suggestion: https://github.com/bcgov/cas-registration/pull/839/commits/b82883e871f4980505d9b557ca30faf103e4d0f3
As always feel free to disagree :)

**Comment by Sepehr-Sobhani** [comment]
@marcellmueller Me again :) This issue is blocking my optimization task. I can work on it in my PR if you haven't fixed it or spent much time on it.

**Comment by marcellmueller** [comment]
@Sepehr-Sobhani I haven't worked on this yet, I just brought it in. Feel free to fix it in your PR, I think your solution looks great thanks!

**Comment by Sepehr-Sobhani** [comment]
Addressed in PD: https://github.com/bcgov/cas-registration/pull/839
