### ISSUE TITLE
Operation status is "Not Started" when it should be "Draft" [6]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#901]
Describe the Bug: As soon as the first page of the Operation form is saved, up until the entire form is submitted, the Operation's status is "Not Started", when it should be "Draft".

Probability (how likely the bug is to happen, scored from 1-5): 3
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 3
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

https://www.loom.com/share/098b79cc9c2d4169a32386eada64ff23

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment]
@nanyangpro , it turned out we never actually had a `Draft` status in the database, so this is less of a bug than a missed feature. Is the following "AC" correct?
- operations have a `Not Started` status when they are imported
- as soon as an industry user saves the first page of the form, the status changes to `Draft`
- the text in the actions column changes to "Continue" (https://www.figma.com/file/LsDmLDCdnJqI8UahyqvOD8/OBPS-App-Designs?type=design&node-id=19-2197&mode=design&t=LM5J4Wo1I55qxz5t-0)
- status changes to `Pending` once the entire form is submitted
- IRC users should not see operations with `Not Started` or `Draft` status

**Comment by nanyangpro** [comment]
Thanks for confirming, @BCerki! Looks accurate to me!
